<?php

namespace DruiD628\Test\Menu\Service;

use PhpSchool\CliMenu\CliMenu;

class MenuObject3 extends AbstractMenu
{
    protected $protectedValue = 'Coral';


    public function __invoke(CliMenu $menu)
    {
        $text = $menu->askText();
        $text->getStyle()
            ->setBg('156')
            ->setFg('237');

        $result = $text->setPlaceholderText("Coral")
            ->ask();
        echo $result->fetch() . "\n";
//        parent::__invoke($menu); // TODO: Change the autogenerated stub
    }
}