<?php

namespace DruiD628\Test\Menu\Service;

use PhpSchool\CliMenu\CliMenu;

class MenuObject2 extends AbstractMenu
{
    public static $NAME = 'NG-529';

    protected $protectedValue = 'Coral';

    public function __invoke(CliMenu $menu): bool
    {
        $text = $menu->askText();
        $text->getStyle()
            ->setBg('156')
            ->setFg('237');

        $result = $text->setPlaceholderText("Coral")
            ->ask();
        echo $result->fetch() . "\n";
//        parent::__invoke($menu); // TODO: Change the autogenerated stub

        return true;
    }
}